import { DIGITS, DOODLES, ML_METRICS, type ModelMetrics } from "./metrics";

/**
 * The model cards: what was trained, how it did, and where the code lives.
 * Server-rendered from src/content/ml-metrics.json (generated by the
 * sketch-lab training repo); the PNGs are training artifacts in public/ml/.
 */

const fmtCount = (n: number) => (n >= 1000 ? `${Math.round(n / 1000)}k` : String(n));
const fmtPct = (x: number) => `${(x * 100).toFixed(1)}%`;
const fmtMB = (b: number) => `${(b / 1_000_000).toFixed(1)} MB`;

function Card({ title, sub, m }: { title: string; sub: string; m: ModelMetrics }) {
  return (
    <div className="gh-card">
      <h3 className="mb-1 text-base font-semibold text-fg">{title}</h3>
      <p className="mb-4 text-sm text-muted">{sub}</p>

      <dl className="mb-4 grid grid-cols-2 gap-x-4 gap-y-2 text-sm sm:grid-cols-4">
        <div>
          <dt className="text-xs text-muted">Test accuracy</dt>
          <dd className="font-semibold text-green">{fmtPct(m.testAccuracy)}</dd>
        </div>
        <div>
          <dt className="text-xs text-muted">Parameters</dt>
          <dd className="font-semibold text-fg">{fmtCount(m.params)}</dd>
        </div>
        <div>
          <dt className="text-xs text-muted">ONNX size</dt>
          <dd className="font-semibold text-fg">{fmtMB(m.modelSizeBytes)}</dd>
        </div>
        <div>
          <dt className="text-xs text-muted">Canvas robustness</dt>
          <dd className="font-semibold text-fg">
            {m.canvasSimAccuracy ? fmtPct(m.canvasSimAccuracy) : "n/a"}
          </dd>
        </div>
      </dl>

      <details className="mb-4 text-sm">
        <summary className="cursor-pointer text-muted hover:text-fg">Architecture</summary>
        <ol className="mt-2 list-inside list-decimal text-muted">
          {m.architecture.map((layer) => (
            <li key={layer}>{layer}</li>
          ))}
        </ol>
        <p className="mt-2 text-xs text-muted">
          Input: 28x28 grayscale, {m.input.range}. Normalization and softmax are baked into the
          ONNX graph (opset {m.opset}), so the browser sends raw ink. Trained {m.trainedAt} with{" "}
          {m.framework}, best of {m.epochs} epochs.
        </p>
      </details>

      <div className="grid gap-3 sm:grid-cols-2">
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          src={m.curvesFile}
          alt={`${title}: training and test loss and accuracy per epoch`}
          className="w-full rounded-md border border-border bg-white"
        />
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          src={m.confusionFile}
          alt={`${title}: test-set confusion matrix`}
          className="w-full rounded-md border border-border bg-white"
        />
      </div>

      <p className="mt-4 text-sm">
        <a href={m.notebookUrl} className="text-link hover:underline" target="_blank" rel="noreferrer">
          Training notebook
        </a>
        <span className="text-muted"> · </span>
        <a href={m.repoUrl} className="text-link hover:underline" target="_blank" rel="noreferrer">
          sketch-lab on GitHub
        </a>
      </p>
    </div>
  );
}

export function ModelCards() {
  return (
    <section aria-labelledby="model-cards-heading" className="mt-12">
      <h2 id="model-cards-heading" className="mb-1 text-lg font-semibold text-fg">
        Under the hood
      </h2>
      <p className="mb-4 max-w-2xl text-sm text-muted">
        Both models are small convolutional networks I trained in PyTorch and exported to ONNX;
        inference runs in your browser through onnxruntime-web (WebAssembly), so nothing you draw
        ever leaves the page. The training code, notebooks, and evaluation gates live in the
        sketch-lab repo.
      </p>
      <div className="grid gap-4 lg:grid-cols-2">
        <Card
          title="Doodle model"
          sub="40 everyday objects, 540k training sketches from the Quick, Draw! dataset."
          m={DOODLES}
        />
        <Card
          title="Digit model"
          sub="MNIST digits with affine and elastic augmentation for mouse-drawn strokes."
          m={DIGITS}
        />
      </div>
      <p className="mt-4 text-xs text-muted">{ML_METRICS.attribution}</p>
    </section>
  );
}
